### PR TITLE
fix: #71 Error 1046: No database selected

### LINKED ISSUE #71: mysql store error: Error 1046: No database selected
Users may see this error after operating the `mysql` store for a while.

A likely cause of this problem is the implementation's use of the MySQL [`USE`](https://dev.mysql.com/doc/refman/8.0/en/use.html) statement: it only applies to the connection in which it is executed.

Golang's `sql/DB` manages a pool of connections. Executing `USE` in one of them does not affect the rest. Also, connections in pools may be recycled after MySQL closes the connection due to idleness.

The implementation needs to ensure `USE` is ran on each connection that will be used to write or read data.

Related: trustbloc/edge-adapter#295

### PR DESCRIPTION
**Pull request by llorllale**
fixes #71

The MySQL `USE` statement is good only for the connection in which it is executed. When the connection is recycled or a different connection is used from the pool managed by sql.DB then the queries don't work.

This patch ensures all queries are executed by referencing the fully-qualified name of the table: `<schema>.<table>`.

This change breaks usage of the store's `Query()` method depending on whether the DSN specifies the database name and whether the query string is using the fully qualified table name.

Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

**Review by talwinder50 — APPROVED** [review]

File: pkg/storage/mysql/mysqlstore.go [hunk 1]
```diff
@@ -165,14 +162,33 @@ func (p *Provider) OpenStore(name string) (storage.Store, error) {
...
+		"SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? LIMIT 1", name, name)
 	if err != nil {
-		return nil, fmt.Errorf(failureWhileExecutingUseQueryErrMsg, name, err)
+		return nil, fmt.Errorf(failureWhileQueryingForTableErrMsg, name, err)
+	}
+
+	defer func() {
+		closeErr := rows.Close()
+		if closeErr != nil {
+			if openErr != nil {
```
Comment (DRK3) [inline pkg/storage/mysql/mysqlstore.go:174]: Isn't `openErr` always nil at this point?

**Review by DRK3 — CHANGES_REQUESTED** [review]

File: pkg/storage/mysql/mysqlstore.go (hunk 1 above)
Comment (DRK3) [reply pkg/storage/mysql/mysqlstore.go:174]: Disregard my previous comment :)

**Review by DRK3 — APPROVED** [review]
