### PR TITLE
fix: not exporting private keys to httpsignature library

### LINKED ISSUE #105: zcaps: httpsignatures.Secrets for 'did:key'
Part of #75 

Task #101 set up tests that required manual importing of a third party's `did:key` into their own Secrets storage. This is should not be required for verification since the verification key is encoded in the `did:key` URL itself.

### LINKED ISSUE #106: zcaps: exposing signing secrets to signature library
part of #75 

The tests in #101 revealed that the `httpsignatures-go` library requires the private key material in order to sign the request. This presents a problem for us because our use cases revolve around the aries-framework-go KMS and Crypto interfaces, which do not expose private keys.

### PR DESCRIPTION
**Pull request by llorllale**
fixes #105
fixes #106 

This PR implements a workaround suggested by the [httpsignatures-go author](https://github.com/igor-pavlenko/httpsignatures-go/issues/5) to avoid passing signing keys to the library.

Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

**Review by DRK3 — APPROVED** [review]

File: pkg/zcapld/middleware.go [hunk 1]
```diff
@@ -42,6 +49,79 @@ type InvocationExpectations struct {
...
+// Create signs data with the secret.
+func (a *AriesDIDKeySignatureHashAlgorithm) Create(secret httpsig.Secret, data []byte) ([]byte, error) {
+	key, err := (&DIDKeyResolver{}).Resolve(secret.KeyID)
+	if err != nil {
+		return nil, fmt.Errorf("failed to resolve did:key URL %s: %w", secret.KeyID, err)
+	}
+
+	// TODO we are assuming curve: https://github.com/trustbloc/edge-core/issues/108.
+	// TODO we shouldn't be using a `localkms` function: https://github.com/trustbloc/edge-core/issues/109.
+	kid, err := localkms.CreateKID(key.Value, kms.ED25519)
```
Comment (Baha-sk) [inline pkg/zcapld/middleware.go:87]: I would pass the key type as an argument to Create()

Comment (Baha-sk) [reply pkg/zcapld/middleware.go:87]: you can also sign using NIST P curves

**Review by Baha-sk — APPROVED** [review]
LGTM, if zcap keys are only limited to ED25519 keys

other key types can be added in the future (if needed)

**Review by aholovko — APPROVED** [review]

File: pkg/zcapld/middleware.go (hunk 1 above)
Comment (llorllale) [reply pkg/zcapld/middleware.go:87]: @Baha-sk 

`Create()` needs to satisfy an interface in `httpsignatures-go`
