### PR TITLE
fix: CouchDBStore GetAll call returns design documents

### LINKED ISSUE #62: CouchDB GetAll method should not return design documents

### PR DESCRIPTION
**Pull request by DRK3**
closes #62 

Signed-off-by: Derek Trider <Derek.Trider@securekey.com>

### CODE REVIEW

**Comment by DRK3** [comment]
Code coverage is a bit low due to some previously untested code being moved inside a conditional.

File: pkg/storage/couchdb/couchdbstore.go [hunk 1]
```diff
@@ -26,6 +26,9 @@ import (
 
 const (
 	logModuleName = "edge-core-couchdbstore"
+
+	designDocumentFilteredOutLogMsg = "Currently getting all documents from a CouchDB store. " +
+		"A document with id %s was filtered out since it appears to be a CouchDB design document."
```
Comment (aholovko) [inline pkg/storage/couchdb/couchdbstore.go:31]: I would change a bit the message here - make it shorter and remove uncertainty: "~Currently~ getting all documents from a CouchDB store. A document with id %s was filtered out ~since it appears to be~ as it's a CouchDB design document."

**Review by aholovko — APPROVED** [review]

File: pkg/storage/couchdb/couchdbstore.go (hunk 1 above)
Comment (DRK3) [reply pkg/storage/couchdb/couchdbstore.go]: Done!
